pipeline {
    agent any
    tools { 
        maven 'maven3.9.6'
        jdk 'jdk21'
    }
    stages {
        stage ('Run tests') {
            steps {
                bat '''
                    cd flightsbooking
                    mvn test -PExpedia
                ''' 
            }
        }
    }
}
